site: Scattered Unoriginal
title: Scattered Unoriginal
#description: >-
#    A collection of scattered thoughts, writings, and experiments
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Boston
data-theme: dark # default theme "dark" | "light"

author:
  name: Christopher Lin
  bio: Lapsed programmer, aspiring brain scientist, and Theory enthusiast 
  username: clin045 # general username
  github: clin045 # github username
  twitter: clin045 # twitter username

# URL settings
url: "https://scatteredunoriginal.com" #
baseurl: "/" # leave blank if not wishd
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


